package net.tarantel.harvestwithease.handler;

import java.util.NoSuchElementException;

import net.tarantel.harvestwithease.HarvestWithEaseLoader;
import net.tarantel.harvestwithease.api.HarvestWithEaseAPI;
import net.tarantel.harvestwithease.config.HarvestWithEaseConfig;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.event.level.BlockEvent;


/**
 *
 */
@Mod.EventBusSubscriber(modid = HarvestWithEaseLoader.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public final class BreakEventHandler {
  /**
   *
   * If configured to do so, drops xp when breaking a mature crop.
   * 
   * @param event
   */
  @SubscribeEvent
  public static void handle(BlockEvent.BreakEvent event) {
    try {
      LevelAccessor world = event.getLevel();
      BlockState blockState = event.getState();
      Block block = blockState.getBlock();
      if (!world.isClientSide() && HarvestWithEaseConfig.getGrantedExp() > 0 && HarvestWithEaseAPI.isBreakableCrop(block) && HarvestWithEaseAPI.isMature(blockState)) {
        block.popExperience((ServerLevel) world, event.getPos(), HarvestWithEaseConfig.getGrantedExp());
      }
    } catch (NullPointerException | NoSuchElementException | ClassCastException e) {
      BlockPos pos = event.getPos();
      HarvestWithEaseLoader.LOGGER.debug("Exception generated by block at [" + pos.getX() + ", " + pos.getY() + ", " + pos.getZ() + "]");
      HarvestWithEaseLoader.LOGGER.debug("This is a non blocking error, but can result in incorrect behavior for mod " + HarvestWithEaseLoader.MODID);
      HarvestWithEaseLoader.LOGGER.debug("Most probably the cause of this issue was that a non-crop ID was added in the configuration and its age property could not be retrieved, see stack trace for more details", e);
    }
  }
}
